### ISSUE TITLE
Back button is not working on pagination

### ISSUE THREAD

**Issue by dkonstantinov193** [Dotnet-Boxed/Templates#783]
### Describe the bug
Looks like links generated for a previous page in pagination is not working and always bring the very first page.

### To Reproduce
1. In swagger execute Get /cars with value 2 in the "First" parameter -> you get 2 first cars.
2. Copy link from "nextPageUrl" and open in the new tab -> you get car 3 & 4.
3. Copy link from "nextPageUrl" and open in the new tab -> you get car 5 & 6.
4. Copy link from "previousPageUrl" and open in the new tab -> you get car 1 & 2.

### Expected behaviour
previous link should open up cars 3 & 4.

### Project template

Boxed Templates 4.6.4

## Environment

VS 16.7.3

**Comment by RehanSaeed** [comment]
Thanks for the bug report. I think the CarRepository needs a bit of work to fix the paging. Want to put up a small PR to fix this?

**Comment by RehanSaeed** [comment]
This should be fixed in https://github.com/Dotnet-Boxed/Templates/pull/794

**Comment by dkonstantinov193** [comment]
Hmm, the issue is still reproducible - when cars split on 3 pages, back link on the last page leading to car 5&3 instead of 1&2
